books:
  0:
    price: 10000
    title: こんなとこ見つける人いる？
    author: ubiquiTAKU
    pages:
      - せっかく変な場所見つけたのに書見台しか置いてないじゃんって思ったよね？知らんけど<br><br>そうなんです何もないんです<br>ロビーにも建築とか何もない悲しい場所いっぱいあるでしょ？<br>建築できる人が居なくて困ってるんだよね
      - ただ人手不足で困ってるのは建築だけじゃないんです<br><br>・プラグイン作成<br>・2D,3Dテクスチャ作成<br>・MythicMobsでのmob作成<br>・サーバー内でのプレイヤーへの対応<br>etc...<br><br>ほぼすべての分野で人手不足が深刻です
      - 何もできなくても運営の中にできる人がいれば教えてくれますたぶん
      - 応募するときはまずサーバーのDiscord(URLは5ページ)に入ってもらって<br>そこの[announcements]とかいう長い名前のとこのピン止めにあると思われるリンクから応募してください...めんどくさくてごめんよ
      - Discord<br>https://discord.gg/bSKUTqJvuZ